window.registerBook({
  "id": "gu-du-de-xiao-pang-xie",
  "title": "孤独的小螃蟹",
  "grade": 2,
  "cover": "images/cover.webp",
  "pages": [
    {
      "image": "images/p1.webp",
      "text": "池塘边的小泥洞里面住着小螃蟹。",
      "pinyin": [
        "chí",
        "táng",
        "biān",
        "de",
        "xiǎo",
        "ní",
        "dòng",
        "lǐ",
        "miàn",
        "zhù",
        "zhe",
        "xiǎo",
        "páng",
        "xiè",
        ""
      ]
    },
    {
      "image": "images/p2.webp",
      "text": "小螃蟹坐在洞口晒太阳。",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "zuò",
        "zài",
        "dòng",
        "kǒu",
        "shài",
        "tài",
        "yáng",
        ""
      ]
    },
    {
      "image": "images/p3.webp",
      "text": "“真舒服啊，”小螃蟹想，“不知道她醒了没有？她总是喜欢在中午睡一会儿。”",
      "pinyin": [
        "",
        "zhēn",
        "shū",
        "fu",
        "a",
        "",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "xiǎng",
        "",
        "",
        "bù",
        "zhī",
        "dào",
        "tā",
        "xǐng",
        "le",
        "méi",
        "yǒu",
        "",
        "tā",
        "zǒng",
        "shì",
        "xǐ",
        "huān",
        "zài",
        "zhōng",
        "wǔ",
        "shuì",
        "yí",
        "huì",
        "er",
        "",
        ""
      ]
    },
    {
      "image": "images/p4.webp",
      "text": "小螃蟹举起他的大钳子，在墙上敲了两下：“咚，咚。”",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "jǔ",
        "qǐ",
        "tā",
        "de",
        "dà",
        "qián",
        "zi",
        "",
        "zài",
        "qiáng",
        "shàng",
        "qiāo",
        "le",
        "liǎng",
        "xià",
        "",
        "",
        "dōng",
        "",
        "dōng",
        "",
        ""
      ]
    },
    {
      "image": "images/p5.webp",
      "text": "隔壁也传来了声音：“笃，笃。”",
      "pinyin": [
        "gé",
        "bì",
        "yě",
        "chuán",
        "lái",
        "le",
        "shēng",
        "yīn",
        "",
        "",
        "dǔ",
        "",
        "dǔ",
        "",
        ""
      ]
    },
    {
      "image": "images/p6.webp",
      "text": "那是住在隔壁的小青蟹敲的。她是小螃蟹的邻居，她的小泥洞和小螃蟹的小泥洞是并排着的。",
      "pinyin": [
        "nà",
        "shì",
        "zhù",
        "zài",
        "gé",
        "bì",
        "de",
        "xiǎo",
        "qīng",
        "xiè",
        "qiāo",
        "de",
        "",
        "tā",
        "shì",
        "xiǎo",
        "páng",
        "xiè",
        "de",
        "lín",
        "jū",
        "",
        "tā",
        "de",
        "xiǎo",
        "ní",
        "dòng",
        "hé",
        "xiǎo",
        "páng",
        "xiè",
        "de",
        "xiǎo",
        "ní",
        "dòng",
        "shì",
        "bìng",
        "pái",
        "zhe",
        "de",
        ""
      ]
    },
    {
      "image": "images/p7.webp",
      "text": "小青蟹爬到洞口来了，用钳子蘸着洞口草叶上的水珠洗脸。",
      "pinyin": [
        "xiǎo",
        "qīng",
        "xiè",
        "pá",
        "dào",
        "dòng",
        "kǒu",
        "lái",
        "le",
        "",
        "yòng",
        "qián",
        "zi",
        "zhàn",
        "zhe",
        "dòng",
        "kǒu",
        "cǎo",
        "yè",
        "shàng",
        "de",
        "shuǐ",
        "zhū",
        "xǐ",
        "liǎn",
        ""
      ]
    },
    {
      "image": "images/p8.webp",
      "text": "小青蟹长得很美。她的颜色那么青，青得像蓝天。她的钳子很小，只有小螃蟹的一半儿大。",
      "pinyin": [
        "xiǎo",
        "qīng",
        "xiè",
        "zhǎng",
        "de",
        "hěn",
        "měi",
        "",
        "tā",
        "de",
        "yán",
        "sè",
        "nà",
        "me",
        "qīng",
        "",
        "qīng",
        "de",
        "xiàng",
        "lán",
        "tiān",
        "",
        "tā",
        "de",
        "qián",
        "zi",
        "hěn",
        "xiǎo",
        "",
        "zhǐ",
        "yǒu",
        "xiǎo",
        "páng",
        "xiè",
        "de",
        "yí",
        "bàn",
        "er",
        "dà",
        ""
      ]
    },
    {
      "image": "images/p9.webp",
      "text": "小螃蟹很喜欢她，总是像大哥哥一样照顾她。",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "hěn",
        "xǐ",
        "huān",
        "tā",
        "",
        "zǒng",
        "shì",
        "xiàng",
        "dà",
        "gē",
        "gē",
        "yí",
        "yàng",
        "zhào",
        "gù",
        "tā",
        ""
      ]
    },
    {
      "image": "images/p10.webp",
      "text": "“快晒会儿太阳吧，”小螃蟹说，“多好的太阳啊。”",
      "pinyin": [
        "",
        "kuài",
        "shài",
        "huì",
        "er",
        "tài",
        "yáng",
        "ba",
        "",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "shuō",
        "",
        "",
        "duō",
        "hǎo",
        "de",
        "tài",
        "yáng",
        "a",
        "",
        ""
      ]
    },
    {
      "image": "images/p11.webp",
      "text": "“嗯。”小青蟹很乖地说，和小螃蟹一样，在洞口坐着。",
      "pinyin": [
        "",
        "ǹg",
        "",
        "",
        "xiǎo",
        "qīng",
        "xiè",
        "hěn",
        "guāi",
        "de",
        "shuō",
        "",
        "hé",
        "xiǎo",
        "páng",
        "xiè",
        "yí",
        "yàng",
        "",
        "zài",
        "dòng",
        "kǒu",
        "zuò",
        "zhe",
        ""
      ]
    },
    {
      "image": "images/p12.webp",
      "text": "太阳就照着他们两个。",
      "pinyin": [
        "tài",
        "yáng",
        "jiù",
        "zhào",
        "zhe",
        "tā",
        "men",
        "liǎng",
        "gè",
        ""
      ]
    },
    {
      "image": "images/p13.webp",
      "text": "小螃蟹睡着了，小青蟹却在想：干吗每天都要晒太阳呢？傻乎乎的……",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "shuì",
        "zháo",
        "le",
        "",
        "xiǎo",
        "qīng",
        "xiè",
        "què",
        "zài",
        "xiǎng",
        "",
        "gàn",
        "má",
        "měi",
        "tiān",
        "dōu",
        "yào",
        "shài",
        "tài",
        "yáng",
        "ne",
        "",
        "shǎ",
        "hū",
        "hū",
        "de",
        "",
        ""
      ]
    },
    {
      "image": "images/p14.webp",
      "text": "她爬过来，用小钳子轻轻地拉拉他。",
      "pinyin": [
        "tā",
        "pá",
        "guò",
        "lái",
        "",
        "yòng",
        "xiǎo",
        "qián",
        "zi",
        "qīng",
        "qīng",
        "de",
        "lā",
        "lā",
        "tā",
        ""
      ]
    },
    {
      "image": "images/p15.webp",
      "text": "“小螃蟹，我要走了。”小青蟹说。",
      "pinyin": [
        "",
        "xiǎo",
        "páng",
        "xiè",
        "",
        "wǒ",
        "yào",
        "zǒu",
        "le",
        "",
        "",
        "xiǎo",
        "qīng",
        "xiè",
        "shuō",
        ""
      ]
    },
    {
      "image": "images/p16.webp",
      "text": "“什么？走？到哪儿去？”小螃蟹醒来了，吓了一跳。",
      "pinyin": [
        "",
        "shén",
        "me",
        "",
        "zǒu",
        "",
        "dào",
        "nǎ",
        "er",
        "qù",
        "",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "xǐng",
        "lái",
        "le",
        "",
        "xià",
        "le",
        "yí",
        "tiào",
        ""
      ]
    },
    {
      "image": "images/p17.webp",
      "text": "“我想去找一个更好的地方住……”",
      "pinyin": [
        "",
        "wǒ",
        "xiǎng",
        "qù",
        "zhǎo",
        "yí",
        "gè",
        "gèng",
        "hǎo",
        "de",
        "dì",
        "fāng",
        "zhù",
        "",
        "",
        ""
      ]
    },
    {
      "image": "images/p18.webp",
      "text": "小螃蟹很吃惊：“难道这个地方不好吗？”",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "hěn",
        "chī",
        "jīng",
        "",
        "",
        "nán",
        "dào",
        "zhè",
        "ge",
        "dì",
        "fāng",
        "bù",
        "hǎo",
        "ma",
        "",
        ""
      ]
    },
    {
      "image": "images/p19.webp",
      "text": "小青蟹轻轻地说：“我也不知道，但是我真的要走了。”",
      "pinyin": [
        "xiǎo",
        "qīng",
        "xiè",
        "qīng",
        "qīng",
        "de",
        "shuō",
        "",
        "",
        "wǒ",
        "yě",
        "bù",
        "zhī",
        "dào",
        "",
        "dàn",
        "shì",
        "wǒ",
        "zhēn",
        "de",
        "yào",
        "zǒu",
        "le",
        "",
        ""
      ]
    },
    {
      "image": "images/p20.webp",
      "text": "“可是，可是……”小螃蟹不知该说什么好。",
      "pinyin": [
        "",
        "kě",
        "shì",
        "",
        "kě",
        "shì",
        "",
        "",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "bù",
        "zhī",
        "gāi",
        "shuō",
        "shén",
        "me",
        "hǎo",
        ""
      ]
    },
    {
      "image": "images/p21.webp",
      "text": "第二天，小螃蟹看到小青蟹时，她已经走远了。",
      "pinyin": [
        "dì",
        "èr",
        "tiān",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "kàn",
        "dào",
        "xiǎo",
        "qīng",
        "xiè",
        "shí",
        "",
        "tā",
        "yǐ",
        "jīng",
        "zǒu",
        "yuǎn",
        "le",
        ""
      ]
    },
    {
      "image": "images/p22.webp",
      "text": "小青蟹转过身来，朝他挥了挥她的小钳子。",
      "pinyin": [
        "xiǎo",
        "qīng",
        "xiè",
        "zhuǎn",
        "guò",
        "shēn",
        "lái",
        "",
        "cháo",
        "tā",
        "huī",
        "le",
        "huī",
        "tā",
        "de",
        "xiǎo",
        "qián",
        "zi",
        ""
      ]
    },
    {
      "image": "images/p23.webp",
      "text": "小螃蟹很难过。",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "hěn",
        "nán",
        "guò",
        ""
      ]
    },
    {
      "image": "images/p24.webp",
      "text": "他用钳子敲敲墙壁：“咚，咚。”那边再也不会传过来“笃，笃”的声音了。",
      "pinyin": [
        "tā",
        "yòng",
        "qián",
        "zi",
        "qiāo",
        "qiāo",
        "qiáng",
        "bì",
        "",
        "",
        "dōng",
        "",
        "dōng",
        "",
        "",
        "nà",
        "biān",
        "zài",
        "yě",
        "bú",
        "huì",
        "chuán",
        "guò",
        "lái",
        "",
        "dǔ",
        "",
        "dǔ",
        "",
        "de",
        "shēng",
        "yīn",
        "le",
        ""
      ]
    },
    {
      "image": "images/p25.webp",
      "text": "小螃蟹一直在洞口坐到天黑。",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "yì",
        "zhí",
        "zài",
        "dòng",
        "kǒu",
        "zuò",
        "dào",
        "tiān",
        "hēi",
        ""
      ]
    },
    {
      "image": "images/p26.webp",
      "text": "小螃蟹心里想：小青蟹现在到哪儿了呢？她是不是每天还会晒会儿太阳呢？她身上还是那么青吗……",
      "pinyin": [
        "xiǎo",
        "páng",
        "xiè",
        "xīn",
        "lǐ",
        "xiǎng",
        "",
        "xiǎo",
        "qīng",
        "xiè",
        "xiàn",
        "zài",
        "dào",
        "nǎ",
        "er",
        "le",
        "ne",
        "",
        "tā",
        "shì",
        "bú",
        "shì",
        "měi",
        "tiān",
        "hái",
        "huì",
        "shài",
        "huì",
        "er",
        "tài",
        "yáng",
        "ne",
        "",
        "tā",
        "shēn",
        "shàng",
        "hái",
        "shì",
        "nà",
        "me",
        "qīng",
        "ma",
        "",
        ""
      ]
    },
    {
      "image": "images/p27.webp",
      "text": "不过，小螃蟹每天睡觉前还是要敲两下墙壁：“咚，咚。”",
      "pinyin": [
        "bú",
        "guò",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "měi",
        "tiān",
        "shuì",
        "jiào",
        "qián",
        "hái",
        "shì",
        "yào",
        "qiāo",
        "liǎng",
        "xià",
        "qiáng",
        "bì",
        "",
        "",
        "dōng",
        "",
        "dōng",
        "",
        ""
      ]
    },
    {
      "image": "images/p28.webp",
      "text": "他是敲给自己听的。",
      "pinyin": [
        "tā",
        "shì",
        "qiāo",
        "gěi",
        "zì",
        "jǐ",
        "tīng",
        "de",
        ""
      ]
    },
    {
      "image": "images/p29.webp",
      "text": "然后，小螃蟹就吐一大堆泡泡，把自己藏起来。他难过的时候，总是这样的。",
      "pinyin": [
        "rán",
        "hòu",
        "",
        "xiǎo",
        "páng",
        "xiè",
        "jiù",
        "tǔ",
        "yí",
        "dà",
        "duī",
        "pào",
        "pao",
        "",
        "bǎ",
        "zì",
        "jǐ",
        "cáng",
        "qǐ",
        "lái",
        "",
        "tā",
        "nán",
        "guò",
        "de",
        "shí",
        "hòu",
        "",
        "zǒng",
        "shì",
        "zhè",
        "yàng",
        "de",
        ""
      ]
    }
  ]
});
